# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Publish to NuGet.org

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Get latest git tag as version
      id: get_version
      run: |
        TAG=$(git describe --tags --abbrev=0)
        VERSION=${TAG#v}  # Strip leading 'v' if present
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: dotnet restore
      run: dotnet restore

    - name: dotnet build
      run: dotnet build --configuration Release --no-restore

    - name: dotnet test
      run: dotnet test --no-build --verbosity normal

    - name: dotnet pack
      run: dotnet pack src/Bk.Cube.Dimension/Bk.Cube.Dimension.csproj --configuration Release --no-build -o ./nupkgs /p:Version=${{ steps.get_version.outputs.version }}

    - name: dotnet nuget push
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

